# Generated by Django 5.1.6 on 2025-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp', '0002_alter_hardware_hardtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='apiTemp',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
