# Generated by Django 5.2 on 2025-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp', '0003_api_apitemp_alter_api_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
    ]
